version: "0.5"

processes:
  uvicorn:
    command: uvicorn backend:app --reload --port 8001
    availability: { restart: always }
    environment:
      - CORS_ORIGIN=http://localhost:8000
  svelte:
    command: vite --port 8000
    availability: { restart: always }
    environment:
      - VITE_BACKEND_URL=http://localhost:8001
